name: Doc Coverage

on:
  push:
    branches:
      - '*'

jobs:
  doc-coverage:
    name: Doc Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Calculate doc coverage
        id: coverage
        uses: bewee/rustdoc-coverage-action@v1
      - name: Print the documented percentage
        run: echo " ${{ steps.coverage.outputs.documented }}"

